version: '2'

services:
    api:
        image: hello-flask
        container_name: hello-flask-api
        build: .
        ports:
           - 80:5000
        environment:
          - consumer_key=
          - consumer_secret=
          - access_token_key=
          - access_token_secret=
        links:
          - mongodb:mongo
          - graylog
        depends_on:
          - mongodb
          - graylog

    mongodb:
      image: mongo:3
      ports:
        - 27017:27017
    
    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.2
      environment:
        - http.host=0.0.0.0
        - transport.host=localhost
        - network.host=0.0.0.0
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      mem_limit: 1g
    
    graylog:
      image: graylog/graylog:3.1
      environment:
        - GRAYLOG_PASSWORD_SECRET=1234567890123456
        # Password: admin
        - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
        # Change to yours Host IP
        #- GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
      links:
        - mongodb:mongo
        - elasticsearch
      depends_on:
        - mongodb
        - elasticsearch
      ports:
        # Graylog web interface and REST API
        - 9000:9000
        # GELF TCP
        - 12201:12201          